### PR TITLE
Report just active app info if there is no active window on MacOS

### PR DESCRIPTION
**Pull request by apiashko**
Use case:
 1. on mac start in terminal: `while true; do echo =============; active-win; sleep 5; done`
 2. launch preferences app
 3. minimize preferences app

result:
 Terminal is active app, but there is no active window
 active-win reports:
```
child_process.js:632
    throw err;
    ^

Error: Command failed: /Users/****/.nvm/versions/node/v14.0.0/lib/node_modules/active-win-cli/node_modules/active-win/main
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:15)
    at Function.module.exports.sync (/Users/****/.nvm/versions/node/v14.0.0/lib/node_modules/active-win-cli/node_modules/active-win/index.js:76:32)
    at Object.<anonymous> (/Users/****/.nvm/versions/node/v14.0.0/lib/node_modules/active-win-cli/cli.js:22:23)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, '', '' ],
  pid: 5267,
  stdout: '',
  stderr: ''
}
```
after the fix active-win reports:
```
{"memoryUsage":"0","title":"","bounds":{"height":0,"y":0,"x":0,"width":0},"owner":{"name":"System Preferences","path":"\/System\/Applications\/System Preferences.app","processId":4759,"bundleId":"com.apple.systempreferences"},"id":0}
```

### CODE REVIEW

**Comment by sindresorhus** [comment]
I don't think this is a good idea. That breaks the guarantees we have set about the return value (even if it preserves the structure and types).

**Comment by apiashko** [comment]
> I don't think this is a good idea. That breaks the guarantees we have set about the return value (even if it preserves the structure and types).

thank you for feedback, 
 let me think about it for a few days. maybe creating active-app package would be better for the use case I have.

**Comment by sindresorhus** [comment]
Just curious, what's your use-case for wanting the active app without window?

**Comment by apiashko** [comment]
I need to log activities on the system. 
active-win is working pretty well for me so far, only a few edge-cases like minimizing current app, or 
display Apple>"About this mac" and minimize it. 
minor really.... but I don't want to give up without giving it a good try.

**Pull request closed without merging**
