### PR TITLE
Switch from fastcall to node-ffi

### PR DESCRIPTION
**Pull request by tiangolo**
Switch to node-ffi, as commented in https://github.com/sindresorhus/active-win/issues/10

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you not modify the comments? They had some minor tweaks.

**Comment by sindresorhus** [comment]
I'll assume you've tested this. I don't have my Windows VM here right now.

**Comment by tiangolo** [comment]
Yep, I'll fix the comments (sorry, didn't notice that).

Yes I manually tested it. 

I even created a package at https://www.npmjs.com/package/@tiangolo/active-win just to test it.

**Comment by sindresorhus** [comment]
I did a major bump, just in case someone depends on how the current cmake thing works.

**Comment by tiangolo** [comment]
Great! Thanks :tada:

**Pull request merged**
