### PR TITLE
Update for Electron 8

### PR DESCRIPTION
**Pull request by wgcv**
Fixes https://github.com/sindresorhus/active-win/issues/68 solved by: @timsu

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you open an issue on ref-napi or Electron?

**Comment by johndalangin** [comment]
Hi @sindresorhus

Confirming that this issue indeed fixes the Electron 8. Would there be any concerns to consider before merging this?

Thank you and stay safe.

**Comment by sindresorhus** [comment]
Yes, when someone does what I commented above. I'm not going to merge a workaround without knowing that it's reported so it can be fixed in the future and the workaround can be reverted.

**Comment by johndalangin** [comment]
Understood thanks 🙏

**Comment by srsholmes** [comment]
@johndalangin @wgcv @timsu Any update on the request of "Can you open an issue on ref-napi or Electron?" 

I'm happy to open the issue, but dont want to duplicate it. Also I dont exactly know what the issue was and how it was solved. It would be good to get this merged when the issue has been opened.

**Comment by wgcv** [comment]
I didn't open a issue.

**Comment by johndalangin** [comment]
@srsholmes I also didn't open an issue as I have limited understanding of the specifics at the moment to credibly open one.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/active-win/issues/68#issuecomment-654167089

**Pull request closed without merging**
